# Crowdreel API Dependencies
# ==========================
source 'http://rubygems.org'

gem 'eventmachine', :git => 'git://github.com/eventmachine/eventmachine.git'
gem 'activesupport', '3.0.0.beta4', :require => nil
gem 'tzinfo'
gem 'i18n'

gem 'zync', :git => 'git://github.com/nulayer/zync.git'

gem 'thin'
